### ISSUE TITLE
Darwin Core For Fun

### ISSUE THREAD

**Issue by lewca** [lewca/Cthulhu-Mythos#1]
I'm wondering what is wrong with the following scheme. Oxygen hits me with an error by line 9.

[DarwinCore.txt](https://github.com/lewca/Cthulhu-Mythos/files/2222106/DarwinCore.txt)

**Comment by mbolam** [comment]
There error at line 9 was just because you had failed to close the angle brackets at the end of line 7. Setting up DarwinCore is a little tricky, so I went ahead and got it together. There are 2 namespaces dwr (records) and dwc (components). Both need to be declared. Rather than trying to limit the schema to just the three elements you listed, I just set it up so any element can be used (just like MODS and DC are set up), then you would document those that are available for your schema in your application profile table. Does that make sense?

I'm attaching the updated schema file and sample xml file (both are text files so I can upload -- just change the extensions to .xsd and .xml to open in Oxygen), so you can see how it looks. Feel free to work from this...

[cthulhu_with_dwr.xsd.txt](https://github.com/lewca/Cthulhu-Mythos/files/2224269/cthulhu_with_dwr.xsd.txt)

[goofy_sample.xml.txt](https://github.com/lewca/Cthulhu-Mythos/files/2224277/goofy_sample.xml.txt)

**Comment by lewca** [comment]
Dude, nice. I wasn't sure you'd see this. Thanks for the corrections and input! Honestly, I perked up when you mentioned the schema in class and just started messing around with it. I'll see what the group thinks about including DarwinCore.

**Comment by mbolam** [comment]
Yeah...it's kind of a funny idea, given that these creatures are fictional (as far as we know), but I'm open for some silly experimentation, because the learning process is the same whether it is science or science fiction.
